apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: policy1
spec:
  validationFailureAction: Enforce
  background: true
  rules:
  - name: check-for-resource-limits
    match:
      any:
      - resources:
          kinds:
          - Pod
    exclude:
      any:
      - resources:
          namespaces:
          - kube-system
          - kyverno
    validate:
      message: "All containers must have CPU and memory requests and limits defined."
      pattern:
        spec:
          containers:
          - resources:
              requests:
                memory: "?*"
                cpu: "?*"
              limits:
                memory: "?*"
                cpu: "?*"
